services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
      - "8888:8888"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--max_old_space_size=4096
    depends_on:
      - backend-dev

  backend-dev:
    container_name: backend-dev
    build:
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app/server
      - ./data:/app/data
      - /app/server/node_modules
    ports:
      - "3000:3000"
